"""Pure data foundation for the forecast-analysis dashboard."""

# Keep the package seam small: adapters and population construction are the public surface.
from .actuals import aggregate_actuals, load_actuals, normalize_actuals
from .analysis_frame import build_analysis_dataset, load_analysis_inputs
from .contracts import (
    ACTUAL_REFERENCE_COLOR,
    AnalysisDataset,
    AnalysisInputs,
    FORECAST_DIRECTIONS,
    HierarchyResult,
    SOURCE_COLORS,
    SOURCE_LABELS,
    VINTAGE_COLORS,
    VINTAGE_LABELS,
    ZERO_REFERENCE_COLOR,
)
from .comparison import ComparisonView, build_source_comparison  # pyright: ignore[reportMissingImports]
from .dashboard import (  # pyright: ignore[reportMissingImports]
    DashboardView,
    build_dashboard_view,
    build_exception_download_frame,
    build_population_summary,
    build_product_detail,
)
from .diagnostics import build_dashboard_diagnostics, build_population_diagnostics
from .quality import QualityView, build_quality_view  # pyright: ignore[reportMissingImports]
from .filters import (  # pyright: ignore[reportMissingImports]
    DashboardFilters,
    apply_actual_filters,
    apply_dashboard_filters,
    apply_quality_pair_filters,
    apply_revision_filters,
    apply_performance_filters,
    available_filter_values,
    with_display_brand,
)
from .forecast_history import load_forecast_history, normalize_forecast_history
from .hierarchy import clean_hierarchy, load_hierarchy, normalize_hierarchy
from .metrics import (  # pyright: ignore[reportMissingImports]
    MetricSummary,
    RevisionMetrics,
    brand_target_metric_definition,
    brand_target_month_order,
    build_brand_target_month_performance,
    build_horizon_audit,
    build_horizon_performance,
    build_monthly_audit,
    build_monthly_performance,
    build_revision_diagnostics,
    build_revision_scatter,
    calculate_metrics,
    calculate_revision_metrics,
    format_horizon_label,
    format_metric,
    format_revision_tolerance,
)
from .sku_classification import (  # pyright: ignore[reportMissingImports]
    SKU_CLASSES,
    SKU_CLASS_UNCLASSIFIED,
    attach_sku_classification,
    build_sku_classifications,
    required_sku_class_actual_months,
)
from .product_history import (  # pyright: ignore[reportMissingImports]
    ProductHistoryView,
    build_product_history,
    search_parent_products,
)
from .product_postmortem import (  # pyright: ignore[reportMissingImports]
    ForwardTreatment,
    ProductPostmortemView,
    TargetMonthSummary,
    build_product_postmortem,
)
from .vintage_accuracy import (
    CommonVintageAccuracy,
    VintageAccuracyRow,
    VintageAccuracySeries,
    build_common_vintage_accuracy,
)
from .vintages import VintageRule, select_vintage_pair  # pyright: ignore[reportMissingImports]

__all__ = [
    "ACTUAL_REFERENCE_COLOR",
    "AnalysisDataset",
    "ComparisonView",
    "CommonVintageAccuracy",
    "QualityView",
    "DashboardFilters",
    "DashboardView",
    "MetricSummary",
    "ProductHistoryView",
    "ProductPostmortemView",
    "ForwardTreatment",
    "TargetMonthSummary",
    "RevisionMetrics",
    "VintageAccuracyRow",
    "VintageAccuracySeries",
    "VintageRule",
    "aggregate_actuals",
    "apply_actual_filters",
    "apply_dashboard_filters",
    "apply_quality_pair_filters",
    "apply_revision_filters",
    "apply_performance_filters",
    "available_filter_values",
    "AnalysisInputs",
    "FORECAST_DIRECTIONS",
    "HierarchyResult",
    "SOURCE_COLORS",
    "SOURCE_LABELS",
    "SKU_CLASSES",
    "SKU_CLASS_UNCLASSIFIED",
    "VINTAGE_COLORS",
    "VINTAGE_LABELS",
    "ZERO_REFERENCE_COLOR",
    "build_analysis_dataset",
    "build_brand_target_month_performance",
    "build_common_vintage_accuracy",
    "build_dashboard_view",
    "build_exception_download_frame",
    "build_population_summary",
    "build_product_detail",
    "build_horizon_audit",
    "build_horizon_performance",
    "build_source_comparison",
    "build_sku_classifications",
    "build_monthly_audit",
    "build_monthly_performance",
    "build_dashboard_diagnostics",
    "build_population_diagnostics",
    "build_quality_view",
    "build_product_history",
    "build_product_postmortem",
    "build_revision_diagnostics",
    "build_revision_scatter",
    "brand_target_metric_definition",
    "brand_target_month_order",
    "calculate_metrics",
    "calculate_revision_metrics",
    "attach_sku_classification",
    "clean_hierarchy",
    "load_actuals",
    "load_analysis_inputs",
    "load_forecast_history",
    "load_hierarchy",
    "normalize_actuals",
    "format_metric",
    "normalize_forecast_history",
    "normalize_hierarchy",
    "required_sku_class_actual_months",
    "format_horizon_label",
    "format_revision_tolerance",
    "search_parent_products",
    "select_vintage_pair",
    "with_display_brand",
]
